Repository explosion/spacy-curated-transformers, pull requests merged in 2024-04, with the labels that each got.

#19 Rebase on `curated-transformers` 2.0.0
  .github/workflows/test.yml
  requirements.txt
  setup.cfg
  spacy_curated_transformers/models/architectures.py
  spacy_curated_transformers/models/hf_loader.py
  spacy_curated_transformers/models/pytorch/__init__.py
  spacy_curated_transformers/models/pytorch/scalar_weight.py
  spacy_curated_transformers/models/scalar_weight.py
  spacy_curated_transformers/tests/models/test_hf_model.py
  spacy_curated_transformers/tests/models/test_transformer_model.py
  spacy_curated_transformers/tests/pipeline/test_transformer.py
  spacy_curated_transformers/tokenization/bbpe_encoder.py
Labels: maintenance

#32 Load models in-place
  project/configs/layer-weighting.cfg
  project/configs/no-layer-weighting.cfg
  requirements.txt
  setup.cfg
  spacy_curated_transformers/cli/fill_config_transformer.py
  spacy_curated_transformers/models/__init__.py
  spacy_curated_transformers/models/architectures.py
  spacy_curated_transformers/models/hf_loader.py
  spacy_curated_transformers/pipeline/transformer.py
  spacy_curated_transformers/tests/models/test_listeners.py
  spacy_curated_transformers/tests/pipeline/test_transformer.py
  spacy_curated_transformers/tests/test_cli_app.py
  spacy_curated_transformers/tests/test_registry.py
Labels: bug, enhancement

#34 Bring back `curated_encoder` prefix
  spacy_curated_transformers/models/architectures.py
  spacy_curated_transformers/models/hf_loader.py
  spacy_curated_transformers/tests/conftest.py
  spacy_curated_transformers/tests/models/test_transformer_model.py
Labels: bug
